name: CI

on:
  push:

jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Run tests
        run: docker run --rm --volume .:/source --workdir /source --tty r1n0x/string-language-tests-runner:1.0.0 composer run-script phpunit-github

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}